### ISSUE TITLE
Zelda 1 crashes in death mountain

### ISSUE THREAD

**Issue by Conn79** [Myself086/Project-Nested#14]
As the title says, it unfortunately crashes in Level 9:

![image122](https://user-images.githubusercontent.com/9334021/127203333-7c3d75f3-ad1b-46eb-a479-08488d49c4d4.jpg)

(Of course I enabled recompile PRG ram, otherwise it won't run at all)

Great work btw ;)

**Comment by Myself086** [comment]
This error is not related to death mountain, just follow step 5 on the exe's main window and it'll reduce RAM usage based on how much of the game you've already seen.

I made a change related to this error in the past few days and will be much less likely to happen in the next release.

**Comment by Myself086** [comment]
I accidentally found your work last night while trying to find something else on google about my project.

I'm not sure what's the best way to distribute profiles for each game, maybe someone can help me set up something.

The compatibility sheet was missing "Disable NMI at vblank" since auto detect is enough for this game. Sometimes having both NMI options causes more crashes.

You can use opcode $22 (JSL) to "escape" the emulation. The emulator will directly copy this instruction and it is the only 65816 instruction that you can use in the NES code when patching a game. I plan to add more patching tools based on demands but so far your work is the only thing that came to fruition.

**Comment by Conn79** [comment]
Yay! The Disable NMI at vblank did the trick :D No more crash... but I am lost where to adjust opcode $22 ro escape emulation

**Comment by Myself086** [comment]
If you patch the NES ROM with opcode $22, which crashes a regular 6502, it'll properly act as a JSL on the emulator so you can have full access to the SNES. Some other $x2 opcodes have been repurposed for patching ROMs.

It looks like you don't need it because you have an IRQ hook but in case you want to edit the original NES code, you will need to know this about the emulator.

**Comment by Conn79** [comment]
Ah I see.
Bad news, it still crashes, but much much less frequently:

https://drive.google.com/file/d/1QoGrDtbSwhYjF60jvUa_WkRTtsA-8xQF/view?usp=sharing
see video at 3:52 mark for crash

Maybe your v1.4 makes it even better :)

As for profiles, maybe some people can make the game profile adjustments, like the attached txt and put it somewhere to dowwnload, or you provide some pre-adjusted game profiles within your download in a provided profiles folder?

[Legend of Zelda, The (USA).txt](https://github.com/Myself086/Project-Nested/files/6896265/Legend.of.Zelda.The.USA.txt)

**Comment by Myself086** [comment]
This game was originally tested way before v1.0 came out and it didn't have any of those crashes. I'm hoping this latest BRK crash is just the indirect JMP crash that I already fixed for the upcoming version. I think the indirect JMP crash is only present in v1.3 so it's worth testing earlier emulator versions for this game.

I noticed that you haven't tried step 5 yet. Your original report was about "Out of Memory" error, not this BRK that you seem to have in all your videos. Step 5 will also improve performance and remove some/most of the hang when something new happens.

**Comment by pepillopev** [comment]
Hi Myself086,
What do you mean with statement "haven't tried step 5"? Is it the Jump range area?

**Comment by Myself086** [comment]
Step 5 on the exe itself as highlighted in this screenshot. If done properly, the number of "known calls" should be greater than 0. There's a bug if you skip step 2 so make sure to do that first.
![image](https://user-images.githubusercontent.com/24799079/127456604-8895db11-34f3-4333-8ae5-41c54c905ee7.png)

**Comment by pepillopev** [comment]
Thanks, doing this helped with stability. So far, no crashes (cross fingers).

**Comment by pepillopev** [comment]
Hi, once again. Simple question, is step 5 unique to the user's unique hardware or emulation environment? In other words, will my profile derived from my SRM benefit others as well? For me, step 5 made a huge improvement; to others not so much.

**Comment by Myself086** [comment]
Use v1.2 for the time being, there's a somewhat rare crash in v1.3 related to indirect JMP list and will be fixed for v1.4.

This "Load SRM" only fixes "Out of Memory" errors. The SRM may be unique per user but can be passed around in the txt file generated for the profile. It contains entry points to sub-routines that need to be recompiled. The exe doesn't attempt to do any of it by itself.

**Comment by Conn79** [comment]
Out of interest, how did you achieve this fantastic work?
I mean we are guessing whether you convert the nes asm into snes asm to execute it via the snes cpu, or if you have a nes cpu somehow inside the rom (nested nes cpu) that executes nes asm instructions?

**Comment by Myself086** [comment]
This is done entirely by the processing power of the SNES. There's no extra processor in the cart. It's just ROM+RAM+Battery.

The exe's role is to merge 2 files together (emulator + NES ROM) and it doesn't attempt to understand the code at all. The iNES header is converted to a different format for faster reads and ROM banks are ordered differently.

This is a recompiler emulator, the recompilation is done on the SNES. Each time unknown code needs to be executed, the recompiler takes some time to rewrite the code in WRAM just-in-time (JIT), this process hangs the game for a fraction of a second each time something new happens. But due to the low amount of WRAM, an "Out of Memory" error will happen, especially with games using mappers. Loading the SRM into the exe lets the exe emulate the emulator (literally) to recompile known sub-routines ahead-of-time (AOT) while the exe gives access to editing ROM. There's almost 2mb of ROM that can be used for recompiled code as opposed to 128kb of WRAM on the SNES. Only about 90kb of WRAM can be used for code due to other data needing space. In v1.4, there will be 256kb of SRAM, 240kb of which is used as extra heap. This extra SRAM is optional and is automatically scaled down based on what's available but the original 16kb must be present.

When Recompiler__Build is called, the following things happen:
- Read and record branches for code blocks. (multi pass)
- Sort code blocks.
- Rewrite code from top to bottom. (single pass)
- Rewrite code for overlapping blocks. (v1.4+)
- Write proper destinations for unsolved jumps. Unsolved branches were coupled with a jump in case it's out of range.
- Transfer new code to ROM (AOT only) or SRAM (JIT only, v1.4+).
- If code was transferred, jumps are adjusted.

Mapper emulation breaks the CPU memory down by blocks of 0x2000 bytes. But because the SNES banks can only switch 32kb at a time, some extra code is added to support switching 8kb or 16kb at a time. This is done by having a variable containing which page range the CPU's DB register represents.
```
	; NES code
	LDA	$8123,x

	; SNES code
	LDA	#$80		; page range requested
	EOR	Memory_NesBank	; using EOR instead of CMP to not ruin carry and overflow flags
	BEQ	+
		JSL	...	; this call has multiple variants
+	LDA	$8123,x
```
Some variants of this code can be surrounded by XBA+XBA and/or PHP+PLP.

I could go into a lot more details but let me know if you have more questions.

**Comment by Conn79** [comment]
That is really impressive, real time compilation of nes code... I do not want to imagine how many hours you needed to get it work, also ~that~ it works. Nobody attempted this before!

**Comment by Myself086** [comment]
The sound emulation was made by Memblers from nesdev.com a long time ago, he lets me use his code for my project. I made some necessary changes to it since. His original data transfer involves 0x17 bytes being transferred 1 by 1 in a loop which costed about 4% of the CPU's time. They are now transferred by using HDMA which is probably why your breakpoints don't trigger on $214x.

**Comment by johneymute** [comment]
Step 5 is the weirdest step off all steps,i was confused about it for a loooooong time untill i understood the meaning it,so what i did was i manually created a 128KB save ram file for my snes powerpak (because with a 8kB sram file i couldn’t store the snes nested learned profile from a nes game on it) 

so once i created a 128KB sram file, i then played a nes game like zelda or mario 2 etc,,, then after when i did enough activities in a nes game and went game over,i then hit and hold reset for 5 seconds then a menu will pop up wich allow you to choose to wich save file you want to save and so i saved on the 128KB sram. File, now once i pull off the cf flash card from the powerpak onto the pc and i had to redo the conversion proccess again BUT this time i added the 128ZkB sram i created and saved nested learned profile on it with the rom sothat after that,i could play that nes game more smoothly,

for the everdrive or snes9x emulator i don’t have to create a save file for it since they do it automatically for you,the only thing you have to do here is just play for a while untill you are gameover or so,then turn off the console or emulator,make sure that it is automatically save, once sure do the reconversion all over again from a nes rom but this time you have to load that srm file with nested file from that game you played on it into the conversion program,now put that converted rom on the everdrive or snes9x emulator,now that game played early on should run smoother with likely minimal to no chance to run out of ram to crash,(you can now throw away that previous converted nes game in favor of the improved converted version you just made)
Yeah i know it’s very weird and it may be hard to understand for some people BUT yes it is and who wants to do twice the same thing just to get things better??? It’s just weird.
